CREATE TABLE [wtur_10min_report](
	[group_id] [nchar](10) NOT NULL,
	[device_id] [smallint] NOT NULL,
	[measure_date] [datetime] NOT NULL,
	[st_OperatingTm] [smallint] NOT NULL,
	[st_StandbyTm] [smallint] NOT NULL,
	[st_StopTm] [smallint] NOT NULL,
	[st_ErrorTm] [smallint] NOT NULL,
	[st_OfflineTm] [smallint] NOT NULL,
	[tur_TotWhMin] [real] NOT NULL,
	[tur_TotWhMax] [real] NOT NULL,
	[tur_TotVArhMin] [real] NOT NULL,
	[tur_TotVArhMax] [real] NOT NULL,
	[tur_TotTmTurMin] [real] NOT NULL,
	[tur_TotTmTurMax] [real] NOT NULL,
	[tur_TotTmTurOkMin] [real] NOT NULL,
	[tur_TotTmTurOkMax] [real] NOT NULL,
	[tur_TotTmTurOpMin] [real] NOT NULL,
	[tur_TotTmTurOpMax] [real] NOT NULL,
	[tur_TurAvl] [float] NOT NULL,
	[tur_StrCntMin] [int] NOT NULL,
	[tur_StrCntMax] [int] NOT NULL,
	[tur_StopCntMin] [int] NOT NULL,
	[tur_StopCntMax] [int] NOT NULL,
	[nac_TotTmNacClMtMin] [real] NOT NULL,
	[nac_TotTmNacClMtMax] [real] NOT NULL,
	[nac_WdSpdNac1sMin] [float] NOT NULL,
	[nac_WdSpdNac1sMax] [float] NOT NULL,
	[nac_WdSpdNac1sAvg] [float] NOT NULL,
	[nac_WdSpdNac1sSDev] [float] NOT NULL,
	[nac_WdSpdNac600s] [float] NOT NULL,
	[nac_WdDir] [float] NOT NULL,
	[nac_NacPos] [float] NOT NULL,
	[nac_NacOutTmp] [float] NOT NULL,
	[nac_NacInTmp] [float] NOT NULL,
	[nac_NacPanlTmp] [float] NOT NULL,
	[nac_YwMis3s] [float] NOT NULL,
	[nac_YwMis30s] [float] NOT NULL,
	[nac_DispZdir] [float] NOT NULL,
	[nac_DispYdir] [float] NOT NULL,
	[nac_WdVane1] [float] NOT NULL,
	[nac_WdVane2] [float] NOT NULL,
	[nac_Anemo1] [float] NOT NULL,
	[nac_Anemo2] [float] NOT NULL,
	[yaw_TotTmYwMtMin] [real] NOT NULL,
	[yaw_TotTmYwMtMax] [real] NOT NULL,
	[yaw_YwCabWup] [float] NOT NULL,
	[rot_TotTmPtMt1Min] [real] NOT NULL,
	[rot_TotTmPtMt1Max] [real] NOT NULL,
	[rot_TotTmPtMt2Min] [real] NOT NULL,
	[rot_TotTmPtMt2Max] [real] NOT NULL,
	[rot_TotTmPtMt3Min] [real] NOT NULL,
	[rot_TotTmPtMt3Max] [real] NOT NULL,
	[rot_RotSpd] [float] NOT NULL,
	[rot_ActPosBlEncA1] [float] NOT NULL,
	[rot_ActPosBlEncA2] [float] NOT NULL,
	[rot_ActPosBlEncA3] [float] NOT NULL,
	[rot_ActPosMotEncA1] [float] NOT NULL,
	[rot_ActPosMotEncA2] [float] NOT NULL,
	[rot_ActPosMotEncA3] [float] NOT NULL,
	[rot_PtAngAtBl1] [float] NOT NULL,
	[rot_PtAngAtBl2] [float] NOT NULL,
	[rot_PtAngAtBl3] [float] NOT NULL,
	[rot_ActSpeedA1] [float] NOT NULL,
	[rot_ActSpeedA2] [float] NOT NULL,
	[rot_ActSpeedA3] [float] NOT NULL,
	[rot_ActBattVoltA1] [float] NOT NULL,
	[rot_ActBattVoltA2] [float] NOT NULL,
	[rot_ActBattVoltA3] [float] NOT NULL,
	[gen_GnSpd] [float] NOT NULL,
	[gen_GnAirEntTmp] [float] NOT NULL,
	[gen_GnAirExTmp] [float] NOT NULL,
	[gen_GnWidTmpU1] [float] NOT NULL,
	[gen_GnWidTmpV1] [float] NOT NULL,
	[gen_GnWidTmpW1] [float] NOT NULL,
	[gen_GnWidTmpU2] [float] NOT NULL,
	[gen_GnWidTmpV2] [float] NOT NULL,
	[gen_GnWidTmpW2] [float] NOT NULL,
	[gen_GnBrgLoadTmp] [float] NOT NULL,
	[gen_GnBrgUnloadTmp] [float] NOT NULL,
	[hyd_TotTmHyTwPmpMtMin] [real] NOT NULL,
	[hyd_TotTmHyTwPmpMtMax] [real] NOT NULL,
	[hyd_TotTmHySysPmpMtMin] [real] NOT NULL,
	[hyd_TotTmHySysPmpMtMax] [real] NOT NULL,
	[hyd_HySysPres] [float] NOT NULL,
	[hyd_HyYwStgPres1] [float] NOT NULL,
	[hyd_HyYwStgPres2] [float] NOT NULL,
	[hyd_HyRtrStgPres] [float] NOT NULL,
	[hyd_HySysOilTmp] [float] NOT NULL,
	[hyd_HyYwOilTmp] [float] NOT NULL,
	[trm_TotTmGbClFnMt1Min] [real] NOT NULL,
	[trm_TotTmGbClFnMt1Max] [real] NOT NULL,
	[trm_TotTmGbClFnMt2Min] [real] NOT NULL,
	[trm_TotTmGbClFnMt2Max] [real] NOT NULL,
	[trm_TotTmGbClPmpMtMin] [real] NOT NULL,
	[trm_TotTmGbClPmpMtMax] [real] NOT NULL,
	[trm_RotBrgTmpA] [float] NOT NULL,
	[trm_RotBrgTmpB] [float] NOT NULL,
	[trm_GbOilTmp] [float] NOT NULL,
	[trm_GbOilPrs] [float] NOT NULL,
	[trm_GbFxBrgHiTmp] [float] NOT NULL,
	[trm_GbFlBrgHiTmp] [float] NOT NULL,
	[trm_GbFxBrgInterTmp] [float] NOT NULL,
	[trm_GbBrgLoTmp] [float] NOT NULL,
	[trm_GbBrgInterTmp] [float] NOT NULL,
	[col_TotTmWtClPmpMtMin] [real] NOT NULL,
	[col_TotTmWtClPmpMtMax] [real] NOT NULL,
	[col_TotTmWtClFn1MtMin] [real] NOT NULL,
	[col_TotTmWtClFn1MtMax] [real] NOT NULL,
	[col_TotTmWtClFn2MtMin] [real] NOT NULL,
	[col_TotTmWtClFn2MtMax] [real] NOT NULL,
	[col_WtColFnInv1] [float] NOT NULL,
	[col_WtColFnInv2] [float] NOT NULL,
	[col_WtColGnInTmp] [float] NOT NULL,
	[col_WtColPCSInTmp] [float] NOT NULL,
	[col_WtColOutTmp] [float] NOT NULL,
	[cnv_Torq] [float] NOT NULL,
	[cnv_TorqRefBack] [float] NOT NULL,
	[cnv_AtPwr] [float] NOT NULL,
	[cnv_ReactPwr] [float] NOT NULL,
	[cnv_WRpm] [float] NOT NULL,
	[cnv_AtA] [float] NOT NULL,
	[cnv_GriV] [float] NOT NULL,
	[cnv_GriA] [float] NOT NULL,
	[cnv_GriFreq] [float] NOT NULL,
	[cnv_GscIGBTTemp] [float] NOT NULL,
	[cnv_LscIGBTTemp] [float] NOT NULL,
	[cnv_PnlIGBTTemp] [float] NOT NULL,
	[trf_TrTmp] [float] NOT NULL,
	[gdc_Hz] [float] NOT NULL,
	[gdc_GdAR] [float] NOT NULL,
	[gdc_GdAS] [float] NOT NULL,
	[gdc_GdAT] [float] NOT NULL,
	[gdc_GdVRS] [float] NOT NULL,
	[gdc_GdVST] [float] NOT NULL,
	[gdc_GdVTR] [float] NOT NULL,
	[gdc_PF] [float] NOT NULL,
	[gdc_TotEgyAtImpMin] [real] NOT NULL,
	[gdc_TotEgyAtImpMax] [real] NOT NULL,
	[gdc_TotEgyAtExpMin] [real] NOT NULL,
	[gdc_TotEgyAtExpMax] [real] NOT NULL,
	[gdc_TotRtImpMin] [real] NOT NULL,
	[gdc_TotRtImpMax] [real] NOT NULL,
	[gdc_TotRtExpMin] [real] NOT NULL,
	[gdc_TotRtExpMax] [real] NOT NULL,
	[gdc_TurWMin] [float] NOT NULL,
	[gdc_TurWMax] [float] NOT NULL,
	[gdc_TurWAvg] [float] NOT NULL,
	[gdc_TurWSDev] [float] NOT NULL,
	[gdc_TurVArMin] [float] NOT NULL,
	[gdc_TurVArMax] [float] NOT NULL,
	[gdc_TurVArAvg] [float] NOT NULL,
	[gdc_TurVArSDev] [float] NOT NULL,
	[gdc_TurAppPw] [float] NOT NULL,
	[etc_field01] [float] NOT NULL,
	[etc_field02] [float] NOT NULL,
	[etc_field03] [float] NOT NULL,
	[etc_field04] [float] NOT NULL,
	[etc_field05] [float] NOT NULL,
	[etc_field06] [float] NOT NULL,
	[etc_field07] [float] NOT NULL,
	[etc_field08] [float] NOT NULL,
	[etc_field09] [float] NOT NULL,
	[etc_field10] [float] NOT NULL,
	[cnv_Gsc1IGBTTemp] [float] NOT NULL,
	[cnv_Gsc2IGBTTemp] [float] NOT NULL,
	[cnv_Lsc1IGBTTemp] [float] NOT NULL,
	[cnv_Lsc2IGBTTemp] [float] NOT NULL,
	[st_fullPerTm] [smallint] NULL,
	[st_parPerTm] [smallint] NULL,
	[st_tecStdbyTm] [smallint] NULL,
	[st_outEnvTm] [smallint] NULL,
	[st_reqShtdnTm] [smallint] NULL,
	[st_outElecSpTm] [smallint] NULL,
	[st_schMtncTm] [smallint] NULL,
	[st_planCorActTm] [smallint] NULL,
	[st_forOutTm] [smallint] NULL,
	[st_suspnTm] [smallint] NULL,
	[st_forMajeuTm] [smallint] NULL,
	[st_inforInvTm] [smallint] NULL,
	[nac_LPFYawMis180s] [real] NULL,
	[rot_SecAvgSpdA1] [real] NULL,
	[rot_SecAvgSpdA2] [real] NULL,
	[rot_SecAvgSpdA3] [real] NULL,
	[trm_GbOilTmp60s] [real] NULL,
	[trm_GbOilPres60s] [real] NULL,
	[trm_GbGenRpm60s] [real] NULL,
	[cnv_LscDcVolt] [real] NULL,
	[gen_GnWidTmpAvg] [real] NULL,
	[trf_TrTmpR] [real] NULL,
	[trf_TrTmpS] [real] NULL,
	[trf_TrTmpT] [real] NULL,
	[rot_RotBrakeTemp] [real] NULL,
	[hyd_RotOilTemp] [real] NULL,
	[cnv_genV] [float] NULL,
	[cnv_genPwr] [float] NULL,
	[cnv_genCosPHI] [float] NULL,
	[nac_Anemo3Min] [float] NULL,
	[nac_Anemo3Max] [float] NULL,
	[nac_Anemo3Avg] [float] NULL,
	[nac_Anemo4Min] [float] NULL,
	[nac_Anemo4Max] [float] NULL,
	[nac_Anemo4Avg] [float] NULL,
	[nac_WdVane3] [float] NULL,
	[nac_WdVane4] [float] NULL,
	[nac_Lidar_vlos1] [float] NULL,
	[nac_Lidar_vlos2] [float] NULL,
	[nac_Lidar_Windspeed1Min] [float] NULL,
	[nac_Lidar_Windspeed1Max] [float] NULL,
	[nac_Lidar_Windspeed1Avg] [float] NULL,
	[nac_Lidar_Windspeed2Min] [float] NULL,
	[nac_Lidar_Windspeed2Max] [float] NULL,
	[nac_Lidar_Windspeed2Avg] [float] NULL,
	[nac_Lidar_Windspeed3Min] [float] NULL,
	[nac_Lidar_Windspeed3Max] [float] NULL,
	[nac_Lidar_Windspeed3Avg] [float] NULL,
	[nac_Lidar_WindAngle1] [float] NULL,
	[nac_Lidar_WindAngle2] [float] NULL,
	[nac_Lidar_WindAngle360] [float] NULL,
	[nac_WdSpdNac1sNTFAvg] [float] NULL,
	[met_Windspeed1Min] [float] NULL,
	[met_Windspeed1Max] [float] NULL,
	[met_Windspeed2Min] [float] NULL,
	[met_Windspeed2Max] [float] NULL,
	[met_Windspeed2Avg] [float] NULL,
	[met_Windspeed3Min] [float] NULL,
	[met_Windspeed3Max] [float] NULL,
	[met_Windspeed3Avg] [float] NULL,
	[met_Winddir1] [float] NULL,
	[met_Winddir2] [float] NULL,
	[met_Winddir3] [float] NULL,
	[met_T_hub] [float] NULL,
	[met_H_hub] [float] NULL,
	[met_T_ref] [float] NULL,
	[met_H_ref] [float] NULL,
	[met_P_hub] [float] NULL,
	[met_Rain] [float] NULL,
	[met_Windspeed1Avg] [float] NULL,
	[cnv_PcsGenFrequency] [float] NULL,
	[cnv_PcsModuleTemp] [float] NULL,
	[cnv_PcsCabinetTemp] [float] NULL,
 CONSTRAINT [PK_wtur_10min_report] PRIMARY KEY CLUSTERED
(
	[group_id] ASC,
	[device_id] ASC,
	[measure_date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]