# 로컬 테스트 용
spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정

  application:
    name: monitoring-local

  security:
    debug: true

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=Monitoring;encrypt=true;trustServerCertificate=true;
    username: sa
    password:
    initialization-mode: always #00. test-data.sql 실행

  jpa:
    hibernate:
      ddl-auto: create-drop # create-drop - 어플리케이션이 종료할때 테이블 삭제
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000 # jpa n+1 문제 예방을 위함.
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/00. test-data.sql

server:
  port: 6789
  servlet:
    session:
      timeout: 43200

## custom setting
cors:
  protocol: http
  ip: 127.0.0.1
  port: 5173
  domain: localhost

api-server:
  ip: 127.0.0.1
  port: 5151
  domain: localhost

batch-server:
  u113: 125.136.87.142
  u113-port: 5151

  u120: 113.160.206.239
  u120-port: 5743

  u151: 125.136.87.155
  u151-port: 5151
