# 로컬 테스트 용
spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정

  application:
    name: batch-local

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=WPPIS_DB_TEST;encrypt=true;trustServerCertificate=true;
    username: sa
    password:
    initialization-mode: always #data.sql 실행

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always
#      schema-locations: classpath:/sql/schema.sql
#      data-locations: classpath:/sql/data.sql