# 로컬 테스트 용
spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정
  r2dbc:
    url: r2dbc:pool:mssql://127.0.0.1:1433/WPPIS_DB_U120
    username: sa
    password:
    pool:
      enabled: true
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
      max-idle-time: 30m
  data:
    r2dbc:
      repositories:
        enabled: true

  application:
    name: batch-local

  datasource:
    initialization-mode: always #data.sql 실행

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
