spring:
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-dev.yml
      - classpath:/yml/application-prod.yml
  profiles:
    active: local  #local, dev, prod
